from datetime import datetime

class WizardEngine:
    """Wizard Engine for managing step-by-step workflows"""
    
    def __init__(self):
        """Initialize the wizard engine"""
        self.wizards = {
            "Site Development Review": {
                "description": "Review site development plans for compliance",
                "icon": "🏗️",
                "steps": [
                    {"name": "Project Information", "type": "form"},
                    {"name": "Zoning Compliance", "type": "checklist"},
                    {"name": "Utility Requirements", "type": "analysis"},
                    {"name": "Drainage Review", "type": "calculation"},
                    {"name": "Final Recommendations", "type": "report"}
                ]
            },
            "Stormwater Permit Review": {
                "description": "Evaluate stormwater management plans",
                "icon": "🌧️",
                "steps": [
                    {"name": "Watershed Analysis", "type": "form"},
                    {"name": "Detention Sizing", "type": "calculation"}, 
                    {"name": "Outlet Design", "type": "checklist"},
                    {"name": "Maintenance Plan", "type": "report"}
                ]
            },
            "Residential Plan Review": {
                "description": "Review residential development applications",
                "icon": "🏘️",
                "steps": [
                    {"name": "Lot Requirements", "type": "checklist"},
                    {"name": "Setback Verification", "type": "calculation"},
                    {"name": "Access Review", "type": "checklist"},
                    {"name": "Utility Connections", "type": "analysis"},
                    {"name": "Final Approval", "type": "report"}
                ]
            }
        }
        
        print(f"✅ Wizard Engine initialized with {len(self.wizards)} workflows")
    
    def get_available_wizards(self):
        """Return available wizard workflows"""
        return self.wizards
    
    def start_wizard(self, wizard_name):
        """Start a wizard workflow"""
        if wizard_name not in self.wizards:
            return {"error": f"Wizard '{wizard_name}' not found"}
        
        wizard_info = self.wizards[wizard_name]
        
        return {
            "wizard_name": wizard_name,
            "current_step": 0,
            "total_steps": len(wizard_info["steps"]),
            "data": {},
            "completed_steps": [],
            "status": "active"
        }
    
    def process_step(self, wizard_state, step_data):
        """Process data from a wizard step"""
        wizard_name = wizard_state["wizard_name"]
        current_step = wizard_state["current_step"]
        
        # Save step data
        wizard_state["data"][f"step_{current_step}"] = step_data
        wizard_state["completed_steps"].append(current_step)
        
        # Move to next step
        wizard_state["current_step"] += 1
        
        # Check if complete
        if wizard_state["current_step"] >= wizard_state["total_steps"]:
            wizard_state["status"] = "complete"
            wizard_state["report"] = self._generate_wizard_report(wizard_state)
        
        return wizard_state
    
    def _generate_wizard_report(self, wizard_state):
        """Generate final report"""
        wizard_name = wizard_state["wizard_name"]
        wizard_info = self.wizards[wizard_name]
        
        report = f"""
{wizard_name.upper()} REPORT
{'=' * 50}

Generated: {self._get_current_timestamp()}

SUMMARY:
This report summarizes the {wizard_name.lower()} workflow completed using the Engineering AI Assistant.

STEPS COMPLETED:
"""
        
        for i, step_info in enumerate(wizard_info["steps"]):
            step_data = wizard_state["data"].get(f"step_{i}", {})
            report += f"\n{i+1}. {step_info['name']}: ✅ Complete"
            
            if step_data:
                report += f"\n   Data: {str(step_data)}"
        
        report += f"""

RECOMMENDATIONS:
- Review all submitted information for accuracy
- Ensure all required documentation is provided
- Schedule follow-up meetings as needed
- Monitor compliance during construction phase

STATUS: Workflow Complete
NEXT STEPS: File for official review and approval

---
Report generated by Engineering AI Assistant
Municipal Engineering Department
"""
        
        return report
    
    def get_step_info(self, wizard_name, step_number):
        """Get information about a specific step"""
        if wizard_name not in self.wizards:
            return None
        
        wizard_info = self.wizards[wizard_name]
        
        if step_number >= len(wizard_info["steps"]):
            return None
        
        return wizard_info["steps"][step_number]
    
    def _get_current_timestamp(self):
        """Get current timestamp"""
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def generate_checklist(self, wizard_name, data=None):
        """Generate checklist for a review type"""
        base_checklists = {
            "Site Development Review": [
                "✅ Site plan drawings provided",
                "✅ Zoning compliance verified", 
                "✅ Setback requirements met",
                "✅ Parking calculations included",
                "✅ Landscaping plan provided",
                "✅ Stormwater management plan included",
                "✅ Utility connection plans shown",
                "✅ Traffic impact considered",
                "✅ Environmental review completed",
                "✅ Fire department access verified"
            ],
            "Stormwater Permit Review": [
                "✅ Watershed delineation provided",
                "✅ Pre-development runoff calculated",
                "✅ Post-development runoff calculated",
                "✅ Detention facility sized appropriately",
                "✅ Outlet structure designed properly",
                "✅ Emergency spillway included",
                "✅ Maintenance access provided",
                "✅ Long-term maintenance plan submitted"
            ],
            "Residential Plan Review": [
                "✅ Lot dimensions meet minimum requirements",
                "✅ Building setbacks comply with zoning",
                "✅ Driveway access meets standards",
                "✅ Utility easements shown",
                "✅ Grading and drainage plan included",
                "✅ Tree protection measures identified",
                "✅ Erosion control plan provided"
            ]
        }
        
        return base_checklists.get(wizard_name, ["✅ Standard review checklist"])
